site_name: Epic Wiki
site_url: https://judebert.github.io/epics-serverless-wiki/
repo_url: https://github.com/judebert/serverless-wiki/wiki
edit_uri: ./_edit
hooks:
  - change_edit_url.py
plugins:
  - search
theme:
  name: material
  features:
    - content.action.edit
